version: '3.8'

services:
  api:
    container_name: 'yalms-api'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - yalms-network
    build:
      context: ./api
      target: prod
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: postgres://postgres:1234@db:5432/yalms?sslmode=disable

  agent:
    deploy:
      replicas: 2
    depends_on:
      - api
    networks:
      - yalms-network
    build:
      context: ./agent
      target: prod
    environment:
      API_URL: http://api:8080
      NUM_WORKERS: 10

  db:
    container_name: 'yalms-database'
    image: postgres:16.1-alpine3.19
    restart: unless-stopped
    environment:
      POSTGRES_DB: yalms
      POSTGRES_PASSWORD: 1234
    ports:
      - "54321:5432"
    networks:
      - yalms-network
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    name: postgres

networks:
  yalms-network: